# Generated by Django 4.2.10 on 2024-02-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_alter_quranchecklist_completed_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quranchecklist',
            name='completed_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quranchecklist',
            name='last_read_surah',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quranchecklist',
            name='last_read_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
