# Generated by Django 4.2.10 on 2024-02-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_alter_quranchecklist_completed_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quranchecklist',
            name='last_read_unit',
        ),
        migrations.AddField(
            model_name='quranchecklist',
            name='target_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quranchecklist',
            name='unit',
            field=models.CharField(blank=True, choices=[('AYAH', 'AYAH'), ('PAGE', 'PAGE'), ('JUZ', 'JUZ'), ('SURAH', 'SURAH')], max_length=255),
        ),
    ]
