# Generated by Django 4.2.10 on 2024-02-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('quran', 'QURAN'), ('hadith', 'HADITH'), ('dua', 'DUA'), ('quote', 'QUOTE')], max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('active_start', models.DateTimeField(blank=True, null=True)),
                ('active_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
